### ISSUE TITLE
Package name confilct

### ISSUE THREAD

**Issue by davidjerleke** [nwidynski/embla-carousel-autoplay#1]
Hi @nwidynski,

- I just finished the official auto scroll plugin for Embla Carousel called `embla-carousel-auto-scroll` and was just about to release it: https://github.com/davidjerleke/embla-carousel/issues/114.

But the CD (continuous deployment) failed because **your package** has a too **similar name**. Could you please [unpublish](https://docs.npmjs.com/unpublishing-packages-from-the-registry) `embla-carousel-autoscroll` so I can publish the package?

<img width="918" alt="embla-carousel-autoscroll" src="https://github.com/nwidynski/embla-carousel-autoplay/assets/11529148/33b8e668-16e0-4af1-82cb-8ce924ca25fc">

Thanks in advance,
David

**Comment by nwidynski** [comment]
Done

**Comment by davidjerleke** [comment]
@nwidynski thank you for your help 👍.
